apiVersion: v1
kind: Namespace
metadata:
  name: production

---
# Web Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Using latest tag!
        ports:
        - containerPort: 80
        # NO RESOURCE LIMITS - dangerous!

      - name: sidecar
        image: busybox  # Another latest tag!
        # NO RESOURCE LIMITS!

---
# Web Service with NodePort
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080

---
# API Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: nodejs
        image: node:latest  # Latest tag again!
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "64Mi"  # Very low memory!
            cpu: "50m"      # Very low CPU!

---
# API Service - CONFLICT with web-service!
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080  # SAME AS web-service!

---
# Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres  # No version tag at all!
        ports:
        - containerPort: 5432
        # NO RESOURCE LIMITS for database!
        env:
        - name: POSTGRES_PASSWORD
          value: "password123"  # Hardcoded password!

---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30080  # ANOTHER CONFLICT!

---
# Monitoring Service - Yet another conflict
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30080  # All using the same port!

  - protocol: TCP
    port: 9090  # Duplicate port in same service!
    targetPort: 9091
    nodePort: 30081

---
# Cache Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: redis
        image: redis:latest  # Latest tag
        ports:
        - containerPort: 6379
        # NO RESOURCE LIMITS!
